config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # CRUD
  # 1. Read
  get '/restaurants', to: "restaurants#index"
  # 2. Create
  get '/restaurants/new', to: "restaurants#new"
  get '/restaurants/:id', to: "restaurants#show", as: :restaurant
  post '/restaurants', to: "restaurants#create"
 # 3. Update
  get '/restaurants/:id/edit', to: "restaurants#edit", as: :edit_restaurant
  patch '/restaurants/:id', to: "restaurants#update"
  # 4. Destroy

  delete 'restaurants/:id', to: "restaurants#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  RATING = [1, 2, 3, 4, 5]
  validates :name, presence: true
  validates :rating, inclusion: { in: RATING }
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
     @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurants_path
    else
      redirect_to :new
    end
  end

  def edit
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to restaurant_path(@restaurant)
    else
      redirect_to edit_restaurant_path(@restaurant)
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end


  private
  # strong params
  def restaurant_params
    params.require(:restaurant).permit(:name, :description, :rating)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TripAdvisor</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for(restaurant) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.label :rating %>
  <%= f.number_field :rating %>
  <%= f.submit %>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Edit restaurant</h1>
<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<ul>
  <% @restaurants.each do |restaurant| %>
     <li> <strong>  <%= restaurant.name %></strong> - <%= link_to "See more", restaurant_path(restaurant)  %> <%= link_to "edit", edit_restaurant_path(restaurant) %>
      <%= link_to "Delete", restaurant_path(restaurant), method: :delete %>
</li>
  <% end %>
</ul>

<%= link_to "Create restaurant", restaurants_new_path %>

app/views/restaurants/new.html.erb
<h1>New restaurant</h1>
<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/show.html.erb
<h1> <%= @restaurant.name %></h1>
<p><%= @restaurant.description %> </p>